### ISSUE TITLE
Increase Coverage

### ISSUE THREAD

**Issue by vinyvicente** [ar2labs/wiring#10]

**Comment by arcostasi** [comment]
Any ideas or suggestions @vinyvicente ? What would you like to increase? Thanks

**Comment by vinyvicente** [comment]
Hi, @arcostasi , this is a permanent task.

**Comment by arcostasi** [comment]
Added [sonarcloud](https://sonarcloud.io/dashboard?id=com.github.ar2labs-wiring) to the project, does anyone know how to display the coverage? Thanks

**Comment by peter279k** [comment]
@arcostasi, we can consider [coveralls ](https://coveralls.io/)or [codecov](https://codecov.io) :).

**Comment by arcostasi** [comment]
Hi @peter279k, I would like to use [sonarcloud](https://sonarcloud.io/dashboard?id=com.github.ar2labs-wiring) coverage with our PHPUnit tests, just show the coverage percentage on sonarcloud dashboard. I'll be working in the next days on [code smells](https://sonarcloud.io/project/issues?id=com.github.ar2labs-wiring&resolved=false&types=CODE_SMELL) fixes. Thanks Peter

**Comment by arcostasi** [comment]
Hi @peter279k and @vinyvicente, All [Code Smells](https://sonarcloud.io/dashboard?id=com.github.ar2labs-wiring) in **Sonar** has been fixed and [coveralls](https://coveralls.io/github/ar2labs/wiring) has been added! The next step is to focus on **coverage** .Thank you guys ;)
