### ISSUE TITLE
Adding coding style check tool

### ISSUE THREAD

**Issue by peter279k** [ar2labs/wiring#16]
As title, I think we can add the `php-cs-fixer` to check PSR-2 coding style during Travis CI build.

It can be automatic to check coding style for upcoming PRs and commits.

**Comment by arcostasi** [comment]
> As title, I think we can add the php-cs-fixer to check PSR-2 coding style during Travis CI build.
> It can be automatic to check coding style for upcoming PRs and commits.

Great Peter, could you add please? Thanks
`php-cs-fixer fix src/ --rules=@PSR2`

**Comment by peter279k** [comment]
Closed via PR #17.
