### ISSUE TITLE
PSR-12: Extended Coding Style

### ISSUE THREAD

**Issue by arcostasi** [ar2labs/wiring#19]
Add new [PSR-12](https://www.php-fig.org/psr/psr-12/) changes to `php_cs.dist`

**Comment by vinyvicente** [comment]
needs await php-cs-fixer implements PSR-12.

**Comment by vinyvicente** [comment]
Keep in mind: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502

**Comment by peter279k** [comment]
@arcostasi, just note that the `PHP_CodeSniffer` has already supported for `PSR-12` coding style.

And it can use `vendor/bin/phpcs --standard=psr12 src tests`.

But never mind, we can still wait for [FriendsOfPHP/PHP-CS-Fixer#4502](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502) :).

**Comment by arcostasi** [comment]
Thanks @peter279k, added support for `PSR-12` coding style.

[Added PSR-12 Extended Coding Style](https://github.com/ar2labs/wiring/commit/19b627b3d95e94c46bfaff6ba8ad1e267e5f6469)
