### ISSUE TITLE
[Question] What's different from aracaw/wiring micro framework?

### ISSUE THREAD

**Issue by peter279k** [ar2labs/wiring#2]
As title, I found that it has the same name, but it's in the different organization.

It's also called [wiring](https://github.com/aracaw/wiring/pull/1).

And what's different from this `ar2labs/wiring`?

**Comment by arcostasi** [comment]
Hi Peter,
Wiring from ar2labs is the second version, many changes from first version to the new release,
It's practically a new project of the same name and the organization has also changed.
You are welcome to collaborate. Thank you.

**Comment by arcostasi** [comment]
We have decided to remove the first version, if anyone needs, please contact me. Thanks!

**Comment by peter279k** [comment]
@arcostasi, I think you can keep this issue open and let the first version I mention be [archive mode](https://help.github.com/en/articles/archiving-a-github-repository).
