### ISSUE TITLE
Nee unit tests for this wiring framework

### ISSUE THREAD

**Issue by peter279k** [ar2labs/wiring#3]
As title, to be reliable for this micro framework, I think we can consider using the `PHPUnit` to complete the unit tests.

P.S. Once this issue is accepted by @arcostasi, I can work on this and create related PR.

**Comment by arcostasi** [comment]
Hi Peter, I really like this and your help is very welcome. 
You have my support. Feel free to do what you can to improve this project and expand to new contributors. Thank you

**Comment by arcostasi** [comment]
Hi Peter,

Follow a project start link for you understand better the process and dependencies
of the Wiring Microframework core.

https://github.com/ar2labs/wiring-start.git

I would like that the Wiring Microframework in the future to be more independent of packages.

For this we will need to develop a Dependency Injection Container with autowiring, PSR-11 compliant, an implementation of the PSR-15 HTTP Server Request Handlers and a unified interface to http routing, PSR-7 compliant.

**Comment by vinyvicente** [comment]
Added tests, missing coverage. Adding issue to help wanted.
